spring:
  application:
    name: fujento

  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password: vin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # usa "update" se vuoi mantenere i dati tra restart
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

user:
  max-preferred-sports: 3
  max-bio-length: 300

